language: python

python:
  - "3.5"

services:
  - docker

install:
  - pip install -q Django==1.11.6
  - pip install django-formtools

before_script:
  - docker pull tp33/django
  - docker pull mysql:5.7.14
  - mkdir -p ~/cs4501/app
  - docker run -it --name web -v ~/cs4501/app:/app tp33/django
  - python
  - import django
  - exit
  - mkdir ~/cs4501/db
  - docker run --name mysql -d -e MYSQL\_ROOT\_PASSWORD='$3cureUS' -v ~/cs4501/db:/var/lib/mysql  mysql:5.7.14
  - docker run -it --name mysql-cmdline --link mysql:db mysql:5.7.14 bash
  - mysql -uroot -p'$3cureUS' -h db
  - create user 'www'@'%' identified by '$3cureUS';
  - create database cs4501 character set utf8;
  - grant all on cs4501.* to 'www'@'%';
  - exit;
  - docker exec -it isa_models_1 bash
  #- "mysql -u root -e 'create database test_cs4501;'"
  #- "mysql -u root -e \"grant all on test_cs4501.* to 'www'@'%';\""

script: python app/models/models/manage.py test

sudo: required
