language: python

python:
  - "3.5"

services:
  - docker

install:
  - pip install -q Django==1.11.6
  - pip install django-formtools

before_script:
  - mkdir ~/db
  - docker pull tp33/django
  - docker pull mysql:5.7.14
  - docker run --name mysql -d -e MYSQL\_ROOT\_PASSWORD='$3cureUS' -v ~/cs4501/db:/var/lib/mysql  mysql:5.7.14
  - docker ps -a
  - sleep 10
  - docker run -it --name mysql-cmdline --link mysql:db mysql:5.7.14 bash -c "mysql -uroot -p'\$3cureUS' -e -h db"
  - -c exit;
  - docker exec -it mysql-cmdline bash -c "mysql -u root -e 'create database test_cs4501;'"
  - docker exec -it mysql-cmdline bash -c "mysql -u root -e \"grant all on test_cs4501.* to 'www'@'%';\"
  #- docker-compose -f docker-compose-test.yml up
  #- docker exec -it models_1 bash
#  - mysql -uroot -p'$3cureUS' -h db
  #- create user 'www'@'%' identified by '$3cureUS';
  #- create database cs4501 character set utf8;
  #- grant all on cs4501.* to 'www'@'%';
  #- exit;
  #- "mysql -u root -e 'create database test_cs4501;'"
  #- "mysql -u root -e \"grant all on test_cs4501.* to 'www'@'%';\""

#script: python app/models/models/manage.py test
script: docker-compose -f docker-compose-test.yml up

sudo: required
