language: python

python:
  - "3.5"

services:
  - docker

install:
  - pip install -q Django==1.11.6
  - pip install django-formtools

before_script:
  - docker pull tp33/django
  - docker pull mysql:5.7.14
  - mysql -uroot -p'$3cureUS' -h db
  - create user 'www'@'%' identified by '$3cureUS';
  - create database cs4501 character set utf8;
  - grant all on cs4501.* to 'www'@'%';
  - exit;
  #- "mysql -u root -e 'create database test_cs4501;'"
  #- "mysql -u root -e \"grant all on test_cs4501.* to 'www'@'%';\""

script: python app/models/models/manage.py test

sudo: required
