 models:
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    command: |
      bash -c '
      python manage.py makemigrations;
      python manage.py migrate;
      python manage.py loaddata initial;
      mod_wsgi-express start-server --working-directory /app --reload-on-changes myProject/wsgi.py
      '
