 models:
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - ./app:/app
    ports:
      - "8001:8000"
    command: |
      bash -c '
      cd /app/models;
      python manage.py makemigrations models;
      python manage.py migrate;
      python manage.py loaddata initial;
      mod_wsgi-express start-server --working-directory /app --reload-on-changes models/wsgi.py
      '
