version: '2'
services:
  spark-master:
    image: gettyimages/spark
    command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
    container_name: spark-master
    #network_mode: "bridge"
    hostname: spark-master
    environment:
      MASTER: spark://spark-master:7077
      SPARK_CONF_DIR: /conf
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    volumes:
      - ./data:/data

  spark-worker:
    image: gettyimages/spark
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    container_name: spark-worker
    #network_mode: "bridge"
    hostname: spark-worker
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 512m
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
    links:
      - spark-master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    ports:
      - 8081:8081
    volumes:
      - ./data:/data

  redis:
    image: redis
    container_name: redis
    network_mode: "bridge"
    ports:
      - "6379:6379"

  kafka:
     image: spotify/kafka
     container_name: kafka
     environment:
        ADVERTISED_HOST: kafka
        ADVERTISED_PORT: 9092
     hostname: kafka
     network_mode: "bridge"

  es:
     image: elasticsearch:2.0
     container_name: es
     network_mode: "bridge"
     ports:
        - "9200:9200"
  models:
     image: tp33/django
     external_links:
        - mysql:db
     ports:
        - "8001:8000"
     volumes:
        - ./app:/app
     network_mode: "bridge"
     command: |
        bash -c '
        cd /app/models;
        python manage.py makemigrations models;
        python manage.py migrate;
        python manage.py loaddata initial;
        mod_wsgi-express start-server --working-directory /app/models --reload-on-changes models/wsgi.py
        '

  exp:
     image: tp33/django
     network_mode: "bridge"
     links:
        - models:models-api
        - kafka:kafka
        - es:es
        - redis:redis
     ports:
        - "8002:8000"
     volumes:
        - ./app:/app
     command: |
        bash -c '
        cd /app/exp;
        pip install requests;
        pip install redis;
        mod_wsgi-express start-server --working-directory /app/exp --reload-on-changes exp/wsgi.py
        '

  web:
     image: tp33/django
     network_mode: "bridge"
     links:
        - exp:exp-api
     ports:
       - 8000
     environment:
       - SERVICE_PORTS=8000
          # - "8000:8000"
     volumes:
        - ./app:/app
     command: |
        bash -c '
        cd /app/web;
        pip3 install requests && mod_wsgi-express start-server --url-alias /static static --working-directory /app/web --reload-on-changes web/wsgi.py
        '

  batch:
     image: tp33/django
     container_name: batch
     network_mode: "bridge"
     volumes:
       - ./es:/es
     links:
       - kafka:kafka
       - es:es
       - models:models-api
     command: |
       bash -c '
       cd /es;
       pip install requests;
       python consume.py
       '
  lb:
     image: dockercloud/haproxy
     network_mode: "bridge"
     links:
       - web
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock
     ports:
       - 8000:80
