test_models:
   image: tp33/django
   external_links:
      - mysql:db
   volumes:
      - ./app:/app
   command: |
      bash -c '
      cd /app/models;
      python manage.py makemigrations models;
      python manage.py migrate;
      python manage.py test
      '
