test_models:
   image: tp33/django
   external_links:
      - mysql:db
   ports:
      - "8001:8000"
   volumes:
      - ./app:/app
   command: |
      bash -c '
      cd /app/models;
      python manage.py makemigrations models;
      python manage.py migrate;
      python manage.py test
      mod_wsgi-express start-server --working-directory /app/models --reload-on-changes models/wsgi.py
      '
kafka:
   image: spotify/kafka
   container_name: kafka
   environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
   hostname: kafka

es:
   image: elasticsearch:2.0
   container_name: es
   ports:
      - "9200:9200"
test_exp:
   image: tp33/django
   external_links:
      - mysql:db
      - kafka:kafka
      - es:es
   volumes:
      - ./app:/app
   command: |
      bash -c '
      cd /app/exp;
      sleep 15;
      python manage.py test
      '
