version: '2'
services:
  redis:
    image: redis
    container_name: redis
    network_mode: "bridge"
    ports:
      - "6379:6379"

  kafka:
     image: spotify/kafka
     container_name: kafka
     environment:
        ADVERTISED_HOST: kafka
        ADVERTISED_PORT: 9092
     hostname: kafka
     network_mode: "bridge"
  
  es:
     image: elasticsearch:2.0
     container_name: es
     network_mode: "bridge"
     ports:
        - "9200:9200"
  models:
     image: tp33/django
     external_links:
        - mysql:db
     ports:
        - "8001:8000"
     volumes:
        - ./app:/app
     network_mode: "bridge"
     command: |
        bash -c '
        cd /app/models;
        python manage.py makemigrations models;
        python manage.py migrate;
        python manage.py loaddata initial;
        mod_wsgi-express start-server --working-directory /app/models --reload-on-changes models/wsgi.py
        '
  
  exp:
     image: tp33/django
     network_mode: "bridge"
     links:
        - models:models-api
        - kafka:kafka
        - es:es
        - redis:redis
     ports:
        - "8002:8000"
     volumes:
        - ./app:/app
     command: |
        bash -c '
        cd /app/exp;
        pip install requests;
        pip install redis;
        mod_wsgi-express start-server --working-directory /app/exp --reload-on-changes exp/wsgi.py
        '
  
  web:
     image: tp33/django
     network_mode: "bridge"
     links:
        - exp:exp-api
     ports:
       - 8000
     environment:
       - SERVICE_PORTS=8000
          # - "8000:8000"
     volumes:
        - ./app:/app
     command: |
        bash -c '
        cd /app/web;
        pip3 install requests && mod_wsgi-express start-server --url-alias /static static --working-directory /app/web --reload-on-changes web/wsgi.py
        '
  
  batch:
     image: tp33/django
     container_name: batch
     network_mode: "bridge"
     volumes:
       - ./es:/es
     links:
       - kafka:kafka
       - es:es
       - models:models-api
     command: |
       bash -c '
       cd /es;
       pip install requests;
       python consume.py
       '
  lb:
     image: dockercloud/haproxy
     network_mode: "bridge"
     links:
       - web
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock
     ports:
       - 8000:80

